### PR TITLE
fix: improve cash register precision

### LINKED ISSUE #559: Cash Register Demo - floating-point error
**Describe the bug**
Demo of the Cash Register project has issue with the floating-point error. Causing it display values with error, and in certain situations, for remaining cash to go below `$0`.

**To Reproduce**
1. Go to https://cash-register.freecodecamp.rocks
2. Enter `330` and submit.
3. Enter `10` and submit.
4. Enter `4` and submit.
5. Enter `4` and submit.

At the step 3. value below status will include the number with clear floating-point error.
After step 5. in register _Nickels_ are below `$0`.

**Expected behavior**
Cash shouldn't go below `$0`, or be displayed with more than a dozen of digits after the dot.

**Screenshots**
image

**Additional context**
- The least time-absorbing solution is adding `toFixed(2)` method to two more places:
https://github.com/freeCodeCamp/demo-projects/blob/a712591fb5cd4cb07ec0efbd8dc2578f4893df1c/apps/cash-register/public/script.js#L66
https://github.com/freeCodeCamp/demo-projects/blob/a712591fb5cd4cb07ec0efbd8dc2578f4893df1c/apps/cash-register/public/script.js#L70

- More robust option is saying _no_ to floats and changing more internals to not do calculations on floats.

### PR DESCRIPTION
**Pull request by gikf**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #559

- - -
- Solution updated to version from https://github.com/freeCodeCamp/freeCodeCamp/pull/55066.
- Added ignored patterns to `.eslintrc.json`, if needed I can use comment to two, currently, affected lines, or create separate PR.

### CODE REVIEW

**Review by lasjorg — APPROVED** [review]
Unlike the current demo code, this code always passes the new last test. I would suggest we merge this to make sure our demo project passes.

---

I see no issue with allowing `_` as an unused var.

File: apps/cash-register/public/script.js [hunk 1]
```diff
@@ -101,18 +105,24 @@ const updateUI = change => {
   };
   // Update cid if change is passed in
   if (change) {
-    change.forEach(changeArr => {
-      const targetArr = cid.find(cidArr => cidArr[0] === changeArr[0]);
-      targetArr[1] = parseFloat((targetArr[1] - changeArr[1]).toFixed(2));
+    change.forEach(([changeDenomination, changeAmount]) => {
+      const targetArr = cid.find(
+        ([denominationName, _]) => denominationName === changeDenomination
```
Comment (naomi-lgbt) [inline apps/cash-register/public/script.js:110]:
```suggestion
        ([denominationName]) => denominationName === changeDenomination
```

This one's not necessary.

**Review by ilenia-magoni — APPROVED** [review]
👍
